# Generated by Django 3.0.7 on 2020-06-17 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Group',
            new_name='CustomGroup',
        ),
    ]
